"""change

Revision ID: 1a1b24ae1608
Revises: d290323a0184
Create Date: 2023-01-17 10:28:03.640109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1b24ae1608'
down_revision = 'd290323a0184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint('from_to', type_='unique')
        batch_op.create_unique_constraint('from_to', ['language_from', 'language_to', 'translatorId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint('from_to', type_='unique')
        batch_op.create_unique_constraint('from_to', ['language_from', 'language_to'])

    # ### end Alembic commands ###
