"""servies model

Revision ID: 7150a5066e32
Revises: 0f339c712fed
Create Date: 2023-01-16 16:26:19.721322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7150a5066e32'
down_revision = '0f339c712fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('translators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_human', sa.Boolean(), nullable=True))
        batch_op.drop_column('language_from')
        batch_op.drop_column('language_to')
        batch_op.drop_column('target_price')
        batch_op.drop_column('min_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_price', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('target_price', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('language_to', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('language_from', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('is_human')

    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
