"""initial

Revision ID: d290323a0184
Revises: 
Create Date: 2023-01-16 22:00:16.729058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd290323a0184'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('change_pass', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_pass')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=True)

    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('change_pass', sa.String(), nullable=True),
    sa.Column('is_human', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_pass')
    )
    with op.batch_alter_table('translators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translators_email'), ['email'], unique=True)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_from', sa.String(), nullable=True),
    sa.Column('language_to', sa.String(), nullable=True),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('target_price', sa.Integer(), nullable=True),
    sa.Column('translatorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['translatorId'], ['translators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_from', 'language_to', name='from_to')
    )
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('language_from', sa.String(), nullable=True),
    sa.Column('language_to', sa.String(), nullable=True),
    sa.Column('deadline', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('statusId', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('translation', sa.String(), nullable=True),
    sa.Column('translatorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['statusId'], ['status.id'], ),
    sa.ForeignKeyConstraint(['translatorId'], ['translators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    op.drop_table('services')
    with op.batch_alter_table('translators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translators_email'))

    op.drop_table('translators')
    op.drop_table('status')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_email'))

    op.drop_table('clients')
    # ### end Alembic commands ###
